#!/bin/bash
SCRIPT_DIR=$( dirname "$0" )
cd $SCRIPT_DIR/../  # Root directory of PyInstaller
# Remove previous files.
rm -r dist
# Create tar.gz for distribution.
python setup.py sdist
python setup.py check
# TODO Sign it.
# Upload it to PYPI.
# Use tool twine for that because it uses encrypted connection.
if [ ! -z "$REPOSITORY" ]; then
    twine upload --repository="$REPOSITORY" dist/*.tar.gz
else
    twine upload dist/*.tar.gz
fi
